Creating Ingress Controller AWS ALB
Link: https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
Youtube: https://www.youtube.com/watch?v=G6_hhVBvgjc

curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.7/docs/install/iam_policy.json
aws iam create-policy \
    --policy-name AWSLoadBalancerControllerIAMPolicy \
    --policy-document file://iam_policy.json
    
eksctl create iamserviceaccount \
  --cluster=prod-eks-cluster \
  --namespace=kube-system \
  --name=aws-load-balancer-controller \
  --role-name AmazonEKSLoadBalancerControllerRole \
  --attach-policy-arn=arn:aws:iam::354009861780:policy/AWSLoadBalancerControllerIAMPolicy \
  --approve

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/master/docs/examples/rbac-role.yaml

# Describe ingress
kubectl get sa -n kube-system
kubectl describe sa alb-ingress-controller -n kube-system


aws iam create-policy \
    --policy-name ALBIngressControllerIAMPolicy \
    --policy-document file://iam_policy_ingress.json 
    
  copy: iam_policy_ingress.json <<  https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/master/docs/examples/iam-policy.json
    
Create Service Account Role:
eksctl create iamserviceaccount \
  --cluster=prod-eks-cluster \
  --region ap-south-1 \
  --namespace=kube-system \
  --name=alb-ingress-controller \
  --role-name alb-ingress-controller-role \
  --attach-policy-arn=arn:aws:iam::354009861780:policy/ALBIngressControllerIAMPolicy \
  --override-existing-serviceaccounts \
  --approve

Verify iamservice account
eksctl get iamserviceaccount --cluster prod-eks-cluster
    
Describe Service Account
kubectl describe sa alb-ingress-controller -n kube-system

Deploy ALB Controller
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/master/docs/examples/alb-ingress-controller.yaml
    
    - check pod status --> ERROR
    - because we have not added the cluster details so,
    
kubectl edit deployment.app/alb-ingress-controller -n kube-system
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
