apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  clusterIP: None
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
